# The key id of a gpg key in the "gpg subdirectory goes here
# You can use the "make gpg-key" helper to create that if you
# full out KEY_USER below
RELEASE_GPG_KEY=91B71A23F6E47ADE395357D3BCE7EC64C08A7741
# This is the gpg key user id that 'make gpg-key' uses for the gpg key
# If you chose to use that to create a gpg id
KEY_USER=matthias.clasen@gmail.com
# The url of your public repository which is embedded in the generated
# .flatpakref file
URL=https://matthiasclasen.github.io/recipes-releases/repo
